# USE_EMBS: false
# D_MODEL: 16
# NUM_HEADS: 2
# DIM_FEEDFORWARD: 128
# NUM_ENCODER_LAYERS: 2
# LAYER_NORM_EPS: 1e-5
# NUM_CLASS: 4
# USE_CRF: true
# ADD_NOISE: false

HIDDEN_CHANNEL: 32
OUT_CHANNEL: 128
TRANSFORMATION:
  REDUCTION_POLICY: 'SKELETON_POOL'
TASK:
  PRETRAIN: false
WEIGHT_PATH: '/home/weihsin/projects/MotionExpert/models_local_new/Local_epoch50.pt'
DATA: 
  TRAIN: '/home/weihsin/datasets/train_Axel_523.pkl'
  TEST: '/home/weihsin/datasets/test_Axel_523.pkl'
  BATCH_SIZE: 2
OPTIMIZER:
  LR: 1e-4
  MAX_EPOCH: 1000
  WARMUP_STEPS: 5000
BRANCH: 2

LOGDIR: ./results/finetune_branch2
ALIGNMENT:
  cfg_file: /home/c1l1mo/projects/VideoAlignment/result/scl_skating_long_50/config.yaml
